# Generated by Django 4.2.7 on 2023-11-22 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Silmarillion',
            fields=[
                ('name', models.CharField(help_text='Введите эпоху (Календарь Нуменора)', max_length=200, primary_key=True, serialize=False, verbose_name='Обитатели Сильмариллиона')),
                ('description', models.TextField(verbose_name='эпоха')),
            ],
            options={
                'db_table': 'sillis',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', help_text='Введите класс', max_length=200, verbose_name='Класс')),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default='Игрок', max_length=200, verbose_name='Ранг в гильдии')),
                ('specie', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silmarin.status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Being',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specie', models.CharField(help_text='Введите расу', max_length=100, verbose_name='Вид')),
                ('name', models.CharField(help_text='Введите Имя', max_length=200, verbose_name='Имя')),
                ('age', models.IntegerField(help_text='Введите возраст', max_length=200, verbose_name='Возраст')),
                ('id_being', models.ForeignKey(blank=True, help_text='Введите уровень владения магии', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Магия')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silmarin.status')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silmarin.silmarillion')),
            ],
            options={
                'db_table': 'Creature',
            },
        ),
    ]
