# Generated by Django 4.2.7 on 2023-12-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('silmarin', '0002_quests'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActingCharacters',
            fields=[
                ('id', models.IntegerField(max_length=200, primary_key=True, serialize=False, verbose_name='Id')),
                ('people', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='silmarin.person')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silmarin.quests')),
            ],
            options={
                'db_table': 'ActingCharacters',
            },
        ),
    ]
